name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Setup Environment..
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Step 1 - Installing dependencies..
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Step 2 - Building packages..
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Step 3 - Running the test..
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
