name: Build and Test @invitato/helpers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Setup Environment..
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installing packages..
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Building pacakges..
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Running test..
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
